In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [ ]:
df=pd.read_csv("Data.csv")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27743 entries, 0 to 27742
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   m49_code                  27743 non-null  int64
 1   country                   27743 non-null  object
 2   region                    1317 non-null   object
 3   cpc_code                  27743 non-null  object
 4   commodity                 27743 non-null  object
 5   year                      27743 non-null  int64
 6   loss_percentage           27743 non-null  float64
 7   loss_percentage_original  27743 non-null  object
 8   loss_quantity             585 non-null    object
 9   activity                  22771 non-null  object
 10  food_supply_stage         24329 non-null  object
 11  treatment                 1410 non-null   object
 12  cause_of_loss             1254 non-null   object
 13  sample_size               1323 non-null   object
 14  method_data_collection    27316 non-null  object
 15  reference                 5800 non-null   object
 16  url                       24287 non-null  object
 17  notes                     2428 non-null   object
dtypes: float64(1), int64(2), object(15)
memory usage: 3.8+ MB

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error

# Step 1: Data Preprocessing
# Select relevant columns
df_selected = df[['country', 'year', 'food_supply_stage', 'loss_percentage']]

# Handle missing values
df_selected.dropna(inplace=True)

# Convert categorical variables into numerical using one-hot encoding
df_encoded = pd.get_dummies(df_selected, columns=['country', 'food_supply_stage'])

# Separate features and target variable
X = df_encoded.drop(columns=['loss_percentage'])
y = df_encoded['loss_percentage']

<ipython-input-24-40f3c026a314>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected.dropna(inplace=True)

In [ ]:
# Step 2: Split the Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
X_train

,m49_code,cpc_code,year,sample_size,reference,url,notes,country_Algeria,country_Angola,country_Argentina,...,method_data_collection_Case Study,method_data_collection_Census,method_data_collection_Controlled Experiment,method_data_collection_Expert Opinion,method_data_collection_FLW Protocol,method_data_collection_Literature Review,method_data_collection_Modelled Estimates,method_data_collection_National Accounts,method_data_collection_No Data Collection Specified,method_data_collection_Survey
25417,840,01221,1985,NaN,NaN,https://www.ers.usda.gov/data-products/food-av...,NaN,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3747,231,0118,2007,NaN,NaN,https://www.aphlis.net/en/data/tables/value-ch...,NaN,False,False,False,...,False,False,False,False,False,False,True,False,False,False
26846,854,0118,2003,NaN,NaN,https://www.aphlis.net/en/data/tables/value-ch...,NaN,False,False,False,...,False,False,False,False,False,False,True,False,False,False
2063,180,0112,2006,NaN,NaN,https://www.aphlis.net/en/data/tables/value-ch...,NaN,False,False,False,...,False,False,False,False,False,False,True,False,False,False
25363,840,01216,1986,NaN,NaN,https://www.ers.usda.gov/data-products/food-av...,NaN,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25344,840,01355.02,1987,NaN,NaN,https://www.ers.usda.gov/data-products/food-av...,NaN,False,False,False,...,False,False,False,False,False,False,False,True,False,False
6174,288,0114,2012,NaN,NaN,https://www.aphlis.net/en/data/tables/value-ch...,NaN,False,False,False,...,False,False,False,False,False,False,True,False,False,False
1006,148,0111,2021,NaN,NaN,https://www.aphlis.net/en/data/tables/value-ch...,NaN,False,False,False,...,False,False,False,False,False,False,True,False,False,False
18839,710,0112,2019,NaN,NaN,https://www.aphlis.net/en/data/tables/value-ch...,NaN,False,False,False,...,False,False,False,False,False,False,True,False,False,False
27438,894,0113,2008,NaN,NaN,https://www.aphlis.net/en/data/tables/value-ch...,NaN,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [ ]:
y_train

10967    4.74732
18824    3.61174
4804     4.46374
23382    8.00000
20221    5.79607
          ...
24791    8.00000
6371     2.36028
1045     3.50000
18303    2.65000
26981    4.39387
Name: loss_percentage, Length: 19463, dtype: float64

In [ ]:
X_test

,year,country_Africa,country_Algeria,country_Angola,country_Argentina,country_Armenia,country_Australia,country_Australia and New Zealand,country_Azerbaijan,country_Bahrain,...,food_supply_stage_Post-harvest,food_supply_stage_Pre-harvest,food_supply_stage_Processing,food_supply_stage_Retail,food_supply_stage_Stacking,food_supply_stage_Storage,food_supply_stage_Trader,food_supply_stage_Transport,food_supply_stage_Whole supply chain,food_supply_stage_Wholesale
15313,2015,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23186,2018,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2083,2005,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4740,2016,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17385,2018,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21319,2002,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13433,2009,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
24896,1995,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
9719,2013,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20518,2000,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
 y_test

15313    4.000000
23186    4.000000
2083     5.263750
4740     0.855431
17385    2.166670
           ...
21319    2.500000
13433    1.130000
24896    4.000000
9719     2.500000
20518    3.500000
Name: loss_percentage, Length: 4866, dtype: float64

In [ ]:
# Step 3: Model Training
# Initialize the SVR (Support Vector Regression) model
regressor = SVR(kernel='linear')

# Train the model on the training data
regressor.fit(X_train, y_train)

# Step 4: Model Evaluation
# Make predictions on the test data
predictions = regressor.predict(X_test)

# Calculate the mean squared error of the model
mse = mean_squared_error(y_test, predictions)
print("Mean Squared Error:", mse)

Mean Squared Error: 34.72443658927631

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27743 entries, 0 to 27742
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   m49_code                  27743 non-null  int64
 1   country                   27743 non-null  object
 2   region                    1317 non-null   object
 3   cpc_code                  27743 non-null  object
 4   commodity                 27743 non-null  object
 5   year                      27743 non-null  int64
 6   loss_percentage           27743 non-null  float64
 7   loss_percentage_original  27743 non-null  object
 8   loss_quantity             585 non-null    object
 9   activity                  22771 non-null  object
 10  food_supply_stage         24329 non-null  object
 11  treatment                 1410 non-null   object
 12  cause_of_loss             1254 non-null   object
 13  sample_size               1323 non-null   object
 14  method_data_collection    27316 non-null  object
 15  reference                 5800 non-null   object
 16  url                       24287 non-null  object
 17  notes                     2428 non-null   object
dtypes: float64(1), int64(2), object(15)
memory usage: 3.8+ MB

In [ ]:
# Convert 'loss_percentage_original' column to numeric, coercing errors
df['loss_percentage_original'] = pd.to_numeric(df['loss_percentage_original'], errors='coerce')

# Drop rows with NaN values in 'loss_percentage_original' column
df.dropna(subset=['loss_percentage_original'], inplace=True)

In [ ]:
# Convert categorical variables into numerical using one-hot encoding
df_encoded = pd.get_dummies(df, columns=['country', 'region', 'commodity', 'activity', 'food_supply_stage', 'treatment', 'cause_of_loss', 'method_data_collection'])

# Separate features (X) and target variable (y)
X = df_encoded.drop(['loss_percentage', 'loss_percentage_original', 'loss_quantity'], axis=1)
y = df_encoded['loss_percentage']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train and evaluate SVM models with different kernels and costs
kernels = ['linear', 'poly', 'rbf']
costs = [1.0, 10.0, 100.0]  # Different costs to try

for kernel in kernels:
    for cost in costs:
        train_and_evaluate_SVM(kernel, C=cost)

TypeError: train_and_evaluate_SVM() missing 4 required positional arguments: 'X_train', 'X_test', 'y_train', and 'y_test'

In [ ]:
print(df_encoded.columns)